apiVersion: 2023-05-01
location: westeurope
name: abajax
properties:
  imageRegistryCredentials:
    - server: abajax.azurecr.io
      username: abajax
      password: password.registry
  containers:
    - name: back
      properties:
        image: abajax.azurecr.io/ab-back:latest
        ports:
          - port: 8000
        resources:
          requests:
            cpu: 1
            memoryInGb: 1.5
    - name: front
      properties:
        image: abajax.azurecr.io/ab-front:latest
        ports:
          - port: 8001
        resources:
          requests:
            cpu: 1
            memoryInGb: 1.5
  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: ab-ajax
    ports:
      - protocol: tcp
        port: 8001
      - protocol: tcp
        port: 8000
tags: {tag: abajax}
type: Microsoft.ContainerInstance/containerGroups