apiVersion: 2023-05-01
location: westeurope
name: abb15    # Needs to match the CONT_NAME in main-deployment.yml
properties:
  imageRegistryCredentials:
      - server: abb15.azurecr.io    # abb15 needs to match the ACR_NAME in main-deployment.yml
        username: abb15    # Same as previous line
        password: password.registry

  containers:
  - name: abb15-front
    properties:
      image: abb15.azurecr.io/ab-front:latest    # Check main-deployment.yml to see full image path to match here
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 8001
  - name: abb15-back
    properties:
      image: abb15.azurecr.io/ab-back:latest    # Check main-deployment.yml to see full image path to match here
      ports:
      - port: 8000
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5

  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: abb15    # Needs to match DNS_NAME in main-deployment.yml
    ports:
    - protocol: tcp
      port: 8001
    - protocol: tcp
      port: 8000

tags: {env: prod}
type: Microsoft.ContainerInstance/containerGroups