apiVersion: 2023-05-01
location: westeurope
name: abb15
properties:
  imageRegistryCredentials:
      - server: abb15.azurecr.io
        username: abb15
        password: password.registry

  containers:
  - name: abb15-front
    properties:
      image: abb15.azurecr.io/ab-front:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 8001
  - name: abb15-back
    properties:
      image: abb15.azurecr.io/ab-back:latest
      ports:
      - port: 8000
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5

  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: abb15
    ports:
    - protocol: tcp
      port: 8001
    - protocol: tcp
      port: 8000

tags: {env: prod-abb15}
type: Microsoft.ContainerInstance/containerGroups