apiVersion: 2023-05-01
location: westeurope
name: ${{ env.CONT_NAME }}
properties:
  imageRegistryCredentials:
      - server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_NAME }}
        password: password.registry

  containers:
  - name: ${{ env.FRONTEND_CONT }}
    properties:
      image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE }}:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 8001
  - name: ${{ env.BACKEND_CONT }}
    properties:
      image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE }}:latest
      ports:
      - port: 8000
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5

  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: ${{ env.DNS_NAME }}
    ports:
    - protocol: tcp
      port: 8001
    - protocol: tcp
      port: 8000

tags: {env: prod-abb15}
type: Microsoft.ContainerInstance/containerGroups