env:
  RG_NAME: RG-ab_b15
  ACR_NAME: abb15
  CONT_NAME: abb15
  
  FRONTEND_IMAGE: ab-front
  BACKEND_IMAGE: ab-back

on:
  push:
    branches:
      - main

name: Services Deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt

      # Generate .pkl files
      - name: Generate .pkl files
        working-directory: ./backend
        run: python pkl_gen.py

       # Login to Azure Container Registry
      - name: Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      # Run tests in backend directory
      - name: Run tests
        working-directory: ./backend
        run: |
          python testing.py
        id: test

      # Build and push frontend Docker image to ACR
      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }}:latest .
          docker tag ${{ env.FRONTEND_IMAGE }}:latest ${{ env.ACR_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE }}:latest
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE }}:latest
        if: steps.test.outcome == 'success'

      # Build and push backend Docker image to ACR
      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build -t ${{ env.BACKEND_IMAGE }}:latest .
          docker tag ${{ env.BACKEND_IMAGE }}:latest ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE }}:latest
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE }}:latest
        if: steps.test.outcome == 'success'

      # Replace the registry password value using my secret
      - name: Find ACR token and replace in config
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "password.registry"
          replace: ${{ secrets.AZURE_ACR_PASSWORD }}
          regex: false
          include: 'acr_config.yml'

      # Delete existing Azure Container Instances for frontend and backend
      - name: Delete existing Azure Container Instances
        run: |
          az container delete --name ${{ env.CONT_NAME }} --resource-group ${{ env.RG_NAME }} --yes
        if: steps.test.outcome == 'success'

      # Create Azure Container Instances for frontend and backend
      - name: Create Azure Container Instances
        run: az container create --resource-group ${{ env.RG_NAME }} --file acr_config.yml
        if: steps.test.outcome == 'success'